In [3]:
with open('input.txt') as f:
    file = f.readlines()
    file = [i.strip() for i in file]

In [4]:
file

['#.#.##.#',
 '#.####.#',
 '...##...',
 '#####.##',
 '#....###',
 '##..##..',
 '#..####.',
 '#...#.#.']

In [3]:
from itertools import product

In [17]:
for x,l in enumerate(file):
    for y,c in enumerate(l):
        if c == "#":
            print((x,y))

(0, 0)
(0, 2)
(0, 4)
(0, 5)
(0, 7)
(1, 0)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 7)
(2, 3)
(2, 4)
(3, 0)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(3, 6)
(3, 7)
(4, 0)
(4, 5)
(4, 6)
(4, 7)
(5, 0)
(5, 1)
(5, 4)
(5, 5)
(6, 0)
(6, 3)
(6, 4)
(6, 5)
(6, 6)
(7, 0)
(7, 4)
(7, 6)


In [1]:
# so this is a super sparse version of the graph
sparseCube = {(x,y) + (0,) for x,l in enumerate(open('input.txt')) for y,c in enumerate(l) if c == "#"}

In [79]:
def a(c):
    n = len(g & set(product(*[range(a-1, a+2) for a in c])))
    return c in g and n == 4 or n == 3

# This solution was stolen, but it's actually also kindof shit. not elegant. The r in this problems could be pretty arbitrary. This solution only really works for this particular scale

In [80]:
for r in range(6):
    g = set(filter(a, product(range(-r-1, r+9), repeat=3)))

In [81]:
print(len(g))

321


In [58]:
product(range(-2-1, 2+8), repeat=3)

# the A function is totally overkill, the function below is closer to an elegant solution as it uses convolutions which are specifically meant for this task

In [12]:
import scipy

In [33]:
import scipy.ndimage

In [34]:
import numpy as np
D = 4

cube = numpy.array([[c == "#" for c in line[:-1]] for line in open('input.txt')])

In [35]:
cube.shape

(8, 8)

In [36]:
cube = np.expand_dims(cube, axis = tuple(range(D - 2)))

In [37]:
cube.shape

(1, 1, 8, 8)

In [42]:
N = numpy.ones(shape = (3,) * D)
N[(1,)*D] = 0

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [52]:
cube  = []

# First solution with conv

In [91]:
def solution(file, dim):
    if dim == 3:
        cube = np.array([[c == "#" for c in line[:-1]] for line in open('input.txt')])
        cube = np.expand_dims(cube, axis = tuple(range(dim-2)))
        filter = np.ones(shape = (3,)*dim)
        filter[(1,)*dim] = 0
        for _ in range(6):
            cube = np.pad(cube, 1).astype(int)
            count = scipy.ndimage.convolve(cube,filter,mode='constant', cval=0)
            cube = (count == 3) & (cube == 0) | (cube == 1) & ((count == 3) | (count == 2))
        print(np.sum(cube))
        return cube
            
    if dim == 4:
        cube = solution(file, 3)
        cube = np.expand_dims(cube, axis= tuple(range(1)))
        filter = np.ones(shape = (4,)*dim)
        filter[(1,)*dim] = 0
        for _ in range(6):
            cube = np.pad(cube, 1).astype(int)
            count = scipy.ndimage.convolve(cube, filter, mode = 'constant', cval = 0)
            cube = (count == 3) & (cube == 0) | (cube == 1) & ((count == 3) | (count == 2))
        print(np.sum(cube))
        

In [92]:
solution('input.txt', 3)

380


array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, Fal

In [86]:
solution('input.txt', 4)

380
(1, 13, 20, 20)
14490


# I misread part2
Though I am keeping the code because I think it would be cool to consider the case where you expand the dimmenions every 6 cycles

In [93]:
def solution(file, dim):
    cube = np.array([[c == "#" for c in line[:-1]] for line in open('input.txt')])
    cube = np.expand_dims(cube, axis = tuple(range(dim-2)))
    filter = np.ones(shape = (3,)*dim)
    filter[(1,)*dim] = 0
    for _ in range(6):
        cube = np.pad(cube, 1).astype(int)
        count = scipy.ndimage.convolve(cube,filter,mode='constant', cval=0)
        cube = (count == 3) & (cube == 0) | (cube == 1) & ((count == 3) | (count == 2))
    print(np.sum(cube))
    return cube

In [95]:
solution('input.txt', 4)

2332


array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa