In [10]:
import numpy as np
from scipy.signal import convolve2d


conv_filter = np.array(
    [
        [1, 1, 1],
        [1, -9, 1],
        [1, 1, 1],
    ]
)


def main():
    with open("small.txt", "r") as f:
        lines = [
            list(map(int, line.replace("L", "1").replace(".", "0")))
            for line in f.read().splitlines()
        ]

    valid_seats = np.array(lines)
    current_state = valid_seats.copy()
    i = 0
    print('first\n',current_state)

    while True:
        next_state = convolve2d(current_state, conv_filter, mode="same")
        print('after conv \n', next_state)
        next_state = np.where(np.logical_or(next_state <= -6, next_state == 0), 1, 0)
        print('after there are full seats next to \n',next_state)
        next_state = np.multiply(valid_seats, next_state)

        if np.array_equal(current_state, next_state):
            return next_state.sum()
        else:
            current_state = next_state


if __name__ == "__main__":
    print(main())

first
 [[1 0 1 1 0 1 1 0 1 1]
 [1 1 1 1 1 1 1 0 1 1]
 [1 0 1 0 1 0 0 1 0 0]
 [1 1 1 1 0 1 1 0 1 1]
 [1 0 1 1 0 1 1 0 1 1]
 [1 0 1 1 1 1 1 0 1 1]
 [0 0 1 0 1 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 0 1 1]]
after conv 
 [[-7  5 -5 -5  5 -5 -6  4 -6 -6]
 [-6 -3 -4 -3 -4 -4 -5  5 -5 -6]
 [-5  8 -3  7 -4  6  5 -5  5  4]
 [-6 -3 -4 -4  5 -5 -5  5 -5 -6]
 [-6  7 -3 -3  7 -3 -4  6 -4 -4]
 [-8  5 -5 -3 -4 -4 -6  4 -6 -6]
 [ 3  6 -4  8 -3  7  5  5  5  4]
 [-7 -4 -4 -2 -3 -3 -4 -5 -5 -7]
 [-6  7 -3 -1 -1 -1 -2 -3  7 -5]
 [-8  4 -6 -4 -4 -4 -5  4 -6 -7]]
after there are full seats next to 
 [[1 0 0 0 0 0 1 0 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 1 1]]
after conv 
 [[-8  2  0  0  0  1 -9  2 -7 -7]
 [-8  2  0  0  0  1  1  2  3 -7]
 [ 2  2  0  0  0  0  0  0  2  2]
 [-8  2  0  0  0  0  0  0  1 -9]
 [-7 

In [11]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])